export type Trade={id:string;date:string;asset:string;market:string;direction:string;entry:number;stop:number;target:number;exit:number;size:number;multiplier:number;fees:number;override:string;setups:string[];timeframe:string;session:string;emotion:string;notes:string;screenshot:string;followed:boolean;violations:string[];demo?:boolean};
export type Goal={id:string;title:string;target:number;current:number};
export type Rule={id:string;text:string};
export type State={version:1;balance:number;trades:Trade[];goals:Goal[];rules:Rule[];checks:Record<string,string[]>};
export const setups=['Liquidity Sweep','MSS','FVG','Order Block','Breaker Block','Other'];
export const checklist=['Analyze market structure','Mark liquidity','Check economic news','Calculate risk','Follow the trading plan','Complete journal'];
export const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export const pnl=(t:Trade)=>{const value=t.override.trim()!==''?Number(t.override):(t.exit-t.entry)*(t.direction==='Long'?1:-1)*t.size*t.multiplier-t.fees;return Math.round((value+Number.EPSILON)*100)/100};
export const risk=(t:Trade)=>Math.abs(t.entry-t.stop)*t.size*t.multiplier;
export const rr=(t:Trade)=>Math.abs(t.entry-t.stop)>0?Math.abs(t.target-t.entry)/Math.abs(t.entry-t.stop):0;
export const result=(t:Trade)=>pnl(t)>0?'Win':pnl(t)<0?'Loss':'Break-even';
export const blank=():Trade=>({id:crypto.randomUUID(),date:today(),asset:'',market:'Forex',direction:'Long',entry:0,stop:0,target:0,exit:0,size:1,multiplier:1,fees:0,override:'',setups:[],timeframe:'5m',session:'New York',emotion:'Calm',notes:'',screenshot:'',followed:true,violations:[]});
export function seed():State{const values=[240,-100,320,180,-120,410,0,-90,270,360,-110,220,190,-100,340,280,420,-130,310,180];return {version:1,balance:10000,rules:[{id:'risk',text:'Risk no more than 1% on a trade'},{id:'limit',text:'Maximum 2 trades per day'},{id:'fomo',text:'No FOMO or revenge entries'}],goals:[{id:'g1',title:'Complete 20 thoughtful trade reviews',target:20,current:8},{id:'g2',title:'Follow my plan for 10 sessions',target:10,current:6}],checks:{},trades:values.map((v,i)=>{const d=new Date();d.setDate(d.getDate()-27+i);return {...blank(),id:`demo-${i}`,date:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,asset:['XAUUSD','EURUSD','BTCUSDT','NAS100'][i%4],market:['Forex','Forex','Crypto','Indices'][i%4],direction:i%3?'Long':'Short',entry:2000,stop:i%3?1990:2010,target:i%3?2030:1970,exit:i%3?2000+v/10:2000-v/10,size:10,override:'',setups:i%2?['Liquidity Sweep','MSS','FVG']:['Order Block','FVG'],emotion:i%5===1?'FOMO':'Calm',followed:i%5!==1,violations:i%5===1?['fomo']:[],notes:'Demo trade — replace with your own market review.',demo:true}})}}
export function validDate(value:unknown):value is string{return typeof value==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(value))&&new Date(value+'T12:00:00Z').toISOString().slice(0,10)===value}
export function validateTrade(t:Trade){if(!validDate(t.date)||t.date>today())return 'Choose a real date on or before today.';if(t.followed&&t.violations.length)return 'A trade with rule violations cannot be marked as following the plan.';if(!Number.isFinite(pnl(t))||!Number.isFinite(risk(t))||!Number.isFinite(rr(t)))return 'Calculated values exceed the supported range.';if(!t.asset.trim()||!/^\d{4}-\d{2}-\d{2}$/.test(t.date))return 'Enter an asset and valid date.';if(![t.entry,t.stop,t.target,t.exit,t.size,t.multiplier,t.fees].every(Number.isFinite)||[t.entry,t.stop,t.target,t.exit,t.size,t.multiplier].some(n=>n<=0)||t.fees<0)return 'Prices, size and multiplier must be positive; fees cannot be negative.';if(t.direction==='Long'&&!(t.stop<t.entry&&t.target>t.entry)||t.direction==='Short'&&!(t.stop>t.entry&&t.target<t.entry))return 'Long: stop below entry, target above. Short: stop above entry, target below.';if(t.override!==''&&!Number.isFinite(Number(t.override)))return 'Enter a valid P&L override.';if(t.screenshot&&!/^https:\/\//.test(t.screenshot)&&!/^data:image\/(png|jpeg|webp);base64,/.test(t.screenshot))return 'Use an HTTPS image URL or a PNG, JPEG or WebP upload.';return ''}
export function validState(x:unknown):x is State{
try{if(!x||typeof x!=='object')return false;const s=x as State;
const unique=(items:{id:string}[])=>items.every(v=>v&&typeof v.id==='string'&&v.id.length>0)&&new Set(items.map(v=>v.id)).size===items.length;
const strings=(v:unknown):v is string[]=>Array.isArray(v)&&v.every(x=>typeof x==='string')&&new Set(v).size===v.length;
return s.version===1&&Number.isFinite(s.balance)&&s.balance>0&&Array.isArray(s.rules)&&unique(s.rules)&&s.rules.every(r=>typeof r.text==='string'&&!!r.text.trim())&&Array.isArray(s.trades)&&unique(s.trades)&&s.trades.every(t=>t&&['override','screenshot','notes','asset','date','market','timeframe','session','emotion'].every(k=>typeof t[k as keyof Trade]==='string')&&['Long','Short'].includes(t.direction)&&typeof t.followed==='boolean'&&(t.demo===undefined||typeof t.demo==='boolean')&&strings(t.setups)&&strings(t.violations)&&t.violations.every(id=>s.rules.some(r=>r.id===id))&&!validateTrade(t))&&Array.isArray(s.goals)&&unique(s.goals)&&s.goals.every(g=>typeof g.title==='string'&&!!g.title.trim()&&Number.isFinite(g.target)&&g.target>0&&Number.isFinite(g.current)&&g.current>=0&&g.current<=g.target)&&!!s.checks&&!Array.isArray(s.checks)&&typeof s.checks==='object'&&Object.entries(s.checks).every(([date,a])=>validDate(date)&&strings(a)&&a.every(v=>checklist.includes(v)))&&Number.isFinite(s.trades.reduce((sum,t)=>sum+pnl(t),s.balance));
}catch{return false}}
